### ISSUE TITLE
pyproject.toml does not appear to be supported

### ISSUE THREAD

**Issue by ciresnave** [CycloneDX/gh-python-generate-sbom#2]
The generator mentions using requirements.txt.  However, the Python community is moving away from using requirements.txt to integrating the build system and all requirements into a pyproject.toml file.  Any chance this will be added to gh-python-generate-sbom?

**Comment by madpah** [comment]
@ciresnave - version 1.1.0 has been released today which adds support for `poetry.lock` parsing.

See https://pypi.org/project/cyclonedx-bom/ for details - would be great to get your feedback.
